<a href="https://colab.research.google.com/github/mubinui/PythonProjects/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(np.__version__)
print(type(arr))

[1 2 3 4 5]
1.19.5
<class 'numpy.ndarray'>


In [ ]:
import numpy as np 
st = tuple((1,6,7,5,7,8))
ar = np.array(st)
print(st)
print(ar)
print(type(st))
print(type(ar))

(1, 6, 7, 5, 7, 8)
[1 6 7 5 7 8]
<class 'tuple'>
<class 'numpy.ndarray'>


In [ ]:
import numpy as np 
arr = np.array(42)
print(arr)
print(type(arr))

42
<class 'numpy.ndarray'>


In [ ]:
#2d array and multidimension array
import numpy as np 
arr = np.array([[2,6,4],[9,6,7],["M","T","D"],["T","L","C"]])
print(arr)
print(arr.ndim)
#Multidimensional arry
a = np.array([[1,2,3,4],["a","b","c","d"]],ndmin = 6)
print(a)
print("number of dimension :",a.ndim)

[['2' '6' '4']
 ['9' '6' '7']
 ['M' 'T' 'D']
 ['T' 'L' 'C']]
2
[[[[[['1' '2' '3' '4']
     ['a' 'b' 'c' 'd']]]]]]
number of dimension : 6


In [ ]:
import numpy as np 

arr = np.array([1,2,3,3,7])
print(arr[0])
print(arr[-1])
arr_01 = np.array([[1,2,3,4,5,6],[2,3,4,46,7,7]])
#printing second element from the first dimension 
print(arr_01[0,1])
print(arr_01[1,3])
#Accessing the items in 3 dim array 
arr_3dim = np.array([[[3,4,6,8],[9,8,6,9]],[[1,2,3,4,],[2,3,4,46,]]])
print(arr_3dim.ndim)
print(arr_3dim[1,1])
print(arr_3dim[1,1,1])
#3d array slicing 
print(arr_3dim[1,1,0:2])

1
7
2
46
3
[ 2  3  4 46]
3
[2 3]


In [ ]:
#Numpy Data types 
import numpy as np
arr = np.array([1,2,3,4])
arr_s = np.array([4,5,6,7],dtype ='S')
print(arr_s)
print(arr_s.dtype)
print(arr.dtype)
arr_s1 = np.array(["Cherry","apple","coconut","rasberry"])
print(arr_s1.dtype)
#Create an array with data type 4 bytes integer
arr_i4 = np.array([1,2,3,4],"i4")
print(arr_i4.dtype)
print(arr_i4)

[b'4' b'5' b'6' b'7']
|S1
int64
<U8
int32
[1 2 3 4]


In [ ]:
# Numpy Array Slicing 
import numpy as np 

arr = np.array([1,2,3,4,5,6,7])
print(arr[1:6:3]) #output [2 5]
print(arr[::2])


[2 5]
[1 3 5 7]


In [ ]:
#Slicing 3d Array 
import numpy as np 
arrcd = np.array([[[[1,2,3],[2,3,4],[1,2,3],[1,2,3]],[[4,5,6],[1,2,3],[4,5,6],[7,8,9]]]])
print(arrcd[0,0,0,:])
print(arrcd.ndim)


[1 2 3]
4


In [ ]:
#Type conversion in python 
import numpy as np 
arr = np.array([1.1,2.2,3.3,4.4,5.5,6.6])
newarray = arr.astype(int)
newarray_02 = newarray.astype(bool)
print(newarray)
print(newarray_02)
print(newarray.dtype)
print(type(newarray))

[1 2 3 4 5 6]
[ True  True  True  True  True  True]
int64
<class 'numpy.ndarray'>


In [ ]:
import numpy as np 
#Difference between View and Copy 
arr = np.array([1,2,3,4,5,6])
x = arr.copy()
arr[0] = 42
print(arr)
print(x)
y = arr.view()
y[0]= 10
print(y)
print(arr)
arr[0] = 25
print(y)

[42  2  3  4  5  6]
[1 2 3 4 5 6]
[10  2  3  4  5  6]
[10  2  3  4  5  6]
[25  2  3  4  5  6]


In [ ]:
import numpy as np 
arr = np.array([[1,2,3,8],[4,5,6,7],[3,5,8,9]])
print(arr.shape) # Prints rows and colom 

a_r = np.array([1,2,3,4,5],ndmin = 5)
print(a_r.shape)
print(a_r)
a_a = np.array([])




#Numpy Array Shape 


(3, 4)
(1, 1, 1, 1, 5)
[[[[[1 2 3 4 5]]]]]


In [ ]:
#Numpy array reshaping 
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12]) 
new_array = arr.reshape(4,3) #2d array 
new_array01 = arr.reshape(3,4) #2d array 
new_array02 = arr.reshape(6,1,2) #3d array
print(new_array)
print(new_array01)
print(new_array02)

# with negetive dim 
arra = np.array([1,2,3,4,5,6,7,8])
newarr = arra.reshape(2,2,-1)
print(newarr)
#flattening the arrays 
newarr04 = new_array.reshape(-1)
print(newarr04) # will print a one dimensional array 



[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[[ 1  2]]

 [[ 3  4]]

 [[ 5  6]]

 [[ 7  8]]

 [[ 9 10]]

 [[11 12]]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
#Numpy array Iterating 
import numpy as np
arr = np.array([[1,2,3,4],[4,5,6,7]])
for x in arr:
    for y in x:
        print(y)


1
2
3
4
4
5
6
7


In [ ]:
import numpy as np 
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [ ]:
# use of nditer
import numpy as np 

arr = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr)
arr01 = np.array([1,2,3])
for x in np.nditer(arr):# help to access all the values 
    print(x)

for x in np.nditer(arr, flags=["buffered"],op_dtypes = ['S']):
    print(x)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
1
2
3
4
5
6
7
8
b'1'
b'2'
b'3'
b'4'
b'5'
b'6'
b'7'
b'8'


In [ ]:
import numpy as np 
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for index , x in np.ndenumerate(arr):# index is a option here best representation 
    print(index,x)


(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [ ]:
#Numpy Array Joining 
import numpy as np 
arr1 = np.array([1,2,3])
arr2 = np.array([4,6,7])
arr = np.concatenate((arr1,arr2))
print(arr)


[1 2 3 4 6 7]


In [ ]:
#joining 2d array alone axis rows (axis = 1)
import numpy as np 
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
arr = np.concatenate((arr1,arr2), axis=0) # (axis =0) adds new row and 
#axis = 1 adds new column 
print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
import numpy as np 
#Joining arrays using stack 
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.stack((arr1,arr2),axis = 1) # axis 1 gives adds columns 
arr_02 = np.stack((arr1,arr2),axis = 0) # axis 0 adds rows 
print(arr_02)
print(arr)
#Stacking along rows hstack horizontal stacking 
arr_hstack  = np.hstack((arr1,arr2)) #horizontal stack
arr_vstack  = np.vstack((arr1,arr2)) #colum wise stack (vertical) 
print(arr_hstack) 
print(arr_vstack)



[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
